EvalReader:
  batch_size: 1
  inputs_def:
    num_max_boxes: 50
  sample_transforms:
  - Decode: {}
  - Resize:
      interp: 2
      keep_ratio: false
      target_size:
      - 608
      - 608
  - NormalizeImage:
      is_scale: true
      mean:
      - 0.485
      - 0.456
      - 0.406
      std:
      - 0.229
      - 0.224
      - 0.225
  - Permute: {}
TestReader:
  batch_size: 1
  inputs_def:
    image_shape:
    - 3
    - 608
    - 608
  sample_transforms:
  - Decode: {}
  - Resize:
      interp: 2
      keep_ratio: false
      target_size:
      - 608
      - 608
  - NormalizeImage:
      is_scale: true
      mean:
      - 0.485
      - 0.456
      - 0.406
      std:
      - 0.229
      - 0.224
      - 0.225
  - Permute: {}
TrainReader:
  batch_size: 1
  batch_transforms:
  - BatchRandomResize:
      keep_ratio: false
      random_interp: true
      random_size: true
      target_size:
      - 320
      - 352
      - 384
      - 416
      - 448
      - 480
      - 512
      - 544
      - 576
      - 608
  - NormalizeBox: {}
  - PadBox:
      num_max_boxes: 50
  - BboxXYXY2XYWH: {}
  - NormalizeImage:
      is_scale: true
      mean:
      - 0.485
      - 0.456
      - 0.406
      std:
      - 0.229
      - 0.224
      - 0.225
  - Permute: {}
  - Gt2YoloTarget:
      anchor_masks:
      - - 6
        - 7
        - 8
      - - 3
        - 4
        - 5
      - - 0
        - 1
        - 2
      anchors:
      - - 10
        - 13
      - - 16
        - 30
      - - 33
        - 23
      - - 30
        - 61
      - - 62
        - 45
      - - 59
        - 119
      - - 116
        - 90
      - - 156
        - 198
      - - 373
        - 326
      downsample_ratios:
      - 32
      - 16
      - 8
  drop_last: true
  inputs_def:
    num_max_boxes: 50
  mixup_epoch: 250
  sample_transforms:
  - Decode: {}
  - Mixup:
      alpha: 1.5
      beta: 1.5
  - RandomDistort: {}
  - RandomExpand:
      fill_value:
      - 123.675
      - 116.28
      - 103.53
  - RandomCrop: {}
  - RandomFlip: {}
  shuffle: true
  use_shared_memory: true
worker_num: 2
